version: "3.8"
services:
  notify:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - $HOME/.aws:/root/.aws
    ports:
      - "8080:8080"
    env_file:
      - ./.env
